#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

homedir='/Users/$(whoami)/'

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# Add global gitignore
ln -s $HOME/.dotfiles/shell/.global-gitignore $HOME/.global-gitignore
git config --global core.excludefile $HOME/.global-gitignore

# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $HOME/.dotfiles/shell/.zshrc $HOME/.zshrc

# Symlink vim prefs
rm $HOME/.vimrc
ln -s $HOME/.dotfiles/shell/.vimrc $HOME/.vimrc
rm $HOME/.vim
ln -s $HOME/.dotfiles/shell/.vim $HOME/.vim

# Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
cd ~/.oh-my-zsh/themes/
git checkout d6a36b1 agnoster.zsh-theme

# Activate z
cd ~/.dotfiles/shell
chmod +x z.sh

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> $homedir
eval "$(/opt/homebrew/bin/brew shellenv)"

echo 'Install node'
echo '------------'
brew install node

echo 'Configure npm'
echo '-------------'
# Create a directory for global packages and tell npm where to store globally installed packages
mkdir "${HOME}/.npm-packages"
npm config set prefix "${HOME}/.npm-packages"

echo 'Install gitmoji-cli'
echo '-------------------'
npm i -g gitmoji-cli

echo 'Install pkg-config'
brew install pkg-config

echo 'Install wget'
echo '------------'
brew install wget

echo 'Install GitHub CLI'
echo '------------------'
brew install gh

echo 'Install GitHub Desktop'
echo '----------------------'
brew install --cask github

echo 'Install PHPStorm'
echo '----------------'
brew install --cask phpstorm

echo 'Install Google Chrome'
echo '---------------------'
brew install --cask google-chrome

echo 'Install Mozilla Firefox'
echo '---------------'
brew install --cask firefox

echo 'Install jq'
echo '----------'
brew install jq

echo 'Install gource'
echo '--------------'
brew install gource

echo 'Install Raycast'
echo '---------------'
brew install --cask raycast

echo 'Install Postman'
echo '---------------'
brew install --cask postman

echo 'Install Ray'
echo '-----------'
brew install --cask ray

echo 'Install Tinkerwell'
echo '------------------'
brew install --cask tinkerwell

echo 'Install HELO'
echo '------------'
brew install --cask helo

echo 'Install Invoker'
echo '---------------'
brew install --cask invoker

echo 'Install TablePlus'
echo '-----------------'
brew install --cask tableplus

echo 'Install Enpass'
echo '--------------'
brew install --cask enpass

echo 'Install Affinity Photo'
echo '----------------------'
brew install --cask affinity-photo

echo 'Install Affinity Designer'
echo '-------------------------'
brew install --cask affinity-designer

echo 'Install Scroll Reverser'
echo '-----------------------'
brew install --cask scroll-reverser

echo 'Install GPG Suite (without Mail)'
echo '--------------------------------'
brew install --cask gpg-suite-no-mail

echo 'Install git-quick-stats'
echo '-----------------------'
brew install --cask git-quick-stats

echo 'Install php'
echo '-----------'
brew install php@8.0
brew link --overwrite --force php@8.0

echo 'Install composer'
echo '----------------'
EXPECTED_COMPOSER_CHECKSUM="$(curl https://composer.github.io/installer.sig)"
php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
ACTUAL_COMPOSER_CHECKSUM="$(php -r "echo hash_file('sha384', 'composer-setup.php');")"
if [ "$EXPECTED_COMPOSER_CHECKSUM" != "$ACTUAL_COMPOSER_CHECKSUM" ]
then
    >&2 echo 'Error: Invalid installer checksum'
    rm composer-setup.php
    exit 1
fi
php composer-setup.php
rm composer-setup.php
mv composer.phar /usr/local/bin/composer

echo 'Install imagemagick'
echo '-------------------'
brew install imagemagick

echo 'Install imagick'
echo '---------------'
pecl install imagick

echo 'Install memcached'
echo '-----------------'
pecl install memcached

echo 'Install xdebug'
echo '--------------'
pecl install xdebug

echo 'Install redis'
echo '-------------'
pecl install redis

echo 'Install laravel valet'
echo '---------------------'
composer global require laravel/valet
valet install

echo 'Install PHP Monitor'
echo '-------------------'
brew tap nicoverbruggen/homebrew-cask
brew install --cask phpmon

echo 'Install watch'
echo '-------------'
brew install watch

echo 'Install pnpm'
echo '------------'
brew install pnpm

echo 'Install fzf'
echo '-----------'
brew install fzf

echo 'Install warp'
echo '------------'
brew install --cask warp

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'All done!'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Set some sensible defaults by running: $HOME/.dotfiles/macos/set-defaults.sh'
echo '2. Make a ~/.dotfiles-custom/shell/.aliases for your personal commands'
echo '3. Make sure to run `fig login` to enable Fig.

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'

